#!/bin/bash

echo "🔧 CORRECTION ERREUR QT SUR VPS"
echo ""
echo "# SOLUTION 1: Build sans interface graphique"
echo "export QT_QPA_PLATFORM=offscreen"
echo "npm run build"
echo ""
echo "# SOLUTION 2: Build uniquement le frontend"
echo "cd /home/ubuntu/JobDone"
echo "npx vite build"
echo ""
echo "# SOLUTION 3: Démarrer sans build (mode développement)"
echo "export NODE_ENV=development"
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"
echo ""
echo "# SOLUTION 4: Nettoyer et rebuild"
echo "rm -rf node_modules"
echo "npm install --production"
echo "npx vite build"