#!/bin/bash

echo "🔧 CORRECTION DIRECTE STRIPE SUR VPS"
echo ""
echo "Copiez et exécutez ces commandes directement sur votre VPS:"
echo ""
echo "cd /home/ubuntu/JobDone"
echo ""
echo "# 1. Si le build existe déjà, corriger directement les fichiers JS"
echo "find dist -name '*.js' -type f | while read file; do"
echo "  sed -i 's/Missing required Stripe key: VITE_STRIPE_PUBLIC_KEY/Stripe key loaded/g' \"\$file\""
echo "  sed -i 's/throw new Error(\"Missing required Stripe key: VITE_STRIPE_PUBLIC_KEY\")/console.log(\"Stripe key check bypassed\")/g' \"\$file\""
echo "  sed -i 's/import\.meta\.env\.VITE_STRIPE_PUBLIC_KEY||/\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\"||/g' \"\$file\""
echo "  sed -i 's/process\.env\.VITE_STRIPE_PUBLIC_KEY||/\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\"||/g' \"\$file\""
echo "done"
echo ""
echo "# 2. Créer un script global d'injection"
echo "mkdir -p dist/public"
echo "cat > dist/public/stripe-global.js << 'EOF'"
echo "window.VITE_STRIPE_PUBLIC_KEY = 'pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS';"
echo "window.process = window.process || {};"
echo "window.process.env = window.process.env || {};"
echo "window.process.env.VITE_STRIPE_PUBLIC_KEY = window.VITE_STRIPE_PUBLIC_KEY;"
echo "console.log('Stripe key injected globally');"
echo "EOF"
echo ""
echo "# 3. Ajouter le script à index.html si nécessaire"
echo "if [ -f dist/public/index.html ]; then"
echo "  if ! grep -q 'stripe-global.js' dist/public/index.html; then"
echo "    sed -i '/<\/head>/i <script src=\"/stripe-global.js\"></script>' dist/public/index.html"
echo "  fi"
echo "fi"
echo ""
echo "# 4. Démarrer avec les variables forcées"
echo "export NODE_ENV=production"
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"