#!/bin/bash

echo "🛠️ SOLUTION IMMÉDIATE POUR VPS"
echo ""
echo "Copiez et exécutez ces commandes sur votre VPS:"
echo ""
echo "cd /home/ubuntu/JobDone"
echo ""
echo "# Option 1 - Build Vite uniquement (sans esbuild qui cause l'erreur Qt):"
echo "npx vite build"
echo ""
echo "# Option 2 - Si même Vite a des problèmes, démarrer en mode dev:"
echo "export NODE_ENV=development"
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"
echo ""
echo "# Option 3 - Forcer la désactivation de Qt:"
echo "export QT_QPA_PLATFORM=offscreen"
echo "export DISPLAY="
echo "unset DISPLAY"
echo "npm run build"