#!/bin/bash

echo "🔥 SOLUTION DÉFINITIVE - ERREUR QT VPS"
echo ""
echo "Exécutez CES COMMANDES sur votre VPS:"
echo ""
echo "cd /home/ubuntu/JobDone"
echo ""
echo "# 1. Builder UNIQUEMENT le frontend (sans esbuild qui cause l'erreur Qt)"
echo "npx vite build"
echo ""
echo "# 2. Si dist/public n'existe pas après le build"
echo "mkdir -p dist/public"
echo "mv dist/* dist/public/ 2>/dev/null || true"
echo ""
echo "# 3. Démarrer l'application"
echo "export NODE_ENV=production"
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"
echo ""
echo "# Alternative si tout échoue - Mode développement direct:"
echo "pkill -f tsx"
echo "export NODE_ENV=development" 
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"