#!/bin/bash

echo "📋 COMMANDES DIRECTES À EXÉCUTER SUR VOTRE VPS:"
echo ""
echo "# Connectez-vous à votre VPS et exécutez ces commandes:"
echo ""
echo "cd /home/ubuntu/JobDone"
echo ""
echo "# 1. Créer le build de production"
echo "npm run build"
echo ""
echo "# 2. Si le build échoue, vérifier la structure"
echo "ls -la dist/"
echo ""
echo "# 3. Si dist/public n'existe pas, le créer"
echo "mkdir -p dist/public"
echo ""
echo "# 4. Si les fichiers sont dans dist/ au lieu de dist/public/"
echo "mv dist/*.html dist/*.js dist/*.css dist/public/ 2>/dev/null || true"
echo "mv dist/assets dist/public/ 2>/dev/null || true"
echo ""
echo "# 5. Démarrer l'application avec les bonnes variables"
echo "export NODE_ENV=production"
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"