#!/bin/bash

# COMMANDES RAPIDES À EXÉCUTER SUR LE VPS

echo "📋 COMMANDES À EXÉCUTER SUR VOTRE VPS:"
echo ""
echo "# 1. Se connecter au VPS:"
echo "ssh ubuntu@purpleguy.world"
echo ""
echo "# 2. Aller dans le dossier de l'application:"
echo "cd /home/ubuntu/JobDone"
echo ""
echo "# 3. Arrêter tout processus en cours:"
echo "pkill -f tsx"
echo "pkill -f node"
echo ""
echo "# 4. Démarrer l'application correctement:"
echo "export NODE_ENV=production"
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"
echo ""
echo "# OU utiliser screen pour garder l'app active:"
echo "screen -S bennespro"
echo "export NODE_ENV=production"
echo "export VITE_STRIPE_PUBLIC_KEY=\"pk_live_51RTkOEH7j6Qmye8ANaVnmmha9hqIUhENTbJo94UZ9D7Ia3hRu7jFbVcBtfO4lJvLiluHxqdproixaCIglmZORP0h00IWlpRCiS\""
echo "npx tsx server/index.ts"
echo "# Puis Ctrl+A+D pour détacher"
echo ""
echo "# Pour voir les logs:"
echo "screen -r bennespro"